### ISSUE TITLE
Mongo save query generating its own UUID causes IllegalArgumentException

### ISSUE THREAD

**Issue by johnoliver** [vert-x/mod-mongo-persistor#33]
When a save is performed with no id field provided, the persister generates a UUID at:

https://github.com/vert-x/mod-mongo-persistor/blob/master/src/main/java/org/vertx/mods/MongoPersistor.java#L169

This causes issues with the mongo java driver, generally IllegalArgumentException when it attempts to read the record back again. This is almost certainly the cause of #21.

This should be resolved by using ObjectID.get() to obtain a valid mongo id and not a UUID. Happy to pull request this however there will be an issue with this as if anyone has relied upon the persister returning a UUID then this will be an API breaking change.

Despite this being an AIP breaking change I think it is necessary as it breaks almost all querying of objects created via save (a temporary workaround is to use upsert as opposed to a save).

**Comment by trepidacious** [comment]
Is this still on course to be accepted? Seems like it would be very useful.

**Comment by karianna** [comment]
We're waiting for the original author of the PR to update it as it doesn't merge.

**Comment by trepidacious** [comment]
I've submitted a pull request with the changes updated to merge, and with use_objectids defaulted to false, new ObjectIds returned in the result, and a simple test case, as https://github.com/vert-x/mod-mongo-persistor/pull/76

**Comment by karianna** [comment]
@johnoliver - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
