### ISSUE TITLE
Support BSON Serialization

### ISSUE THREAD

**Issue by erturne** [vert-x/mod-mongo-persistor#35]
JSON is lossy. If I send a message containing a java.util.Date on the Vert.x event bus it appears to be serialized as a number, and stored in MongoDB as a NumberLong. For various reasons I would like dates to be stored as dates in MongoDB.

If the mongo persistor could parse BSON then dates could be retained as dates because BSON supports date datatypes.

The mongo persistor could default to parsing JSON, but be configured to parse BSON.

**Comment by karianna** [comment]
@erturne - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
