### ISSUE TITLE
Better support for paged result sets

### ISSUE THREAD

**Issue by patrickvankann** [vert-x/mod-mongo-persistor#36]
REST APIs and web UIs often feature the ability to navigate back and forth through "pages" of data. In order to support this functionality properly, it is necessary to know the size of the full result set in addition to the "skip" and "limit" numbers that set the page boundaries. Otherwise, you cannot determine whether to show a "next" link or calculate the number of pages in the result set.

Currently, this is possible only by making two separate requests on mod-mongo-persistor - one for the results using "find", and another for the count using "count".

I would like a way of retrieving both the results and the count in a single message. This could be done two ways that i can immediately think of:

1. Add a "count" field to the batch message returned from "find" that contains the result of "curser.count()". I don't believe this adds significant overhead to a "find" query. But it does change the content of the "find" response message, which could break existing clients (backwards compatibility).

2. Create a new "findPaged" request that has this functionality - and in addition, would return the original "skip" and "limit" along with status, results and count field of the "find" method. Both skip and limit would be mandatory parameters, unlike "find". Common functionality between "find" and "findPaged" would need to be refactored into shared methods. I don't think batch processing is needed, since by definition results would be limited to a subset of the whole. A maximum size could be enforced to ensure this is not abused.

This would not break existing clients but would increase the size and complexity of the class.

I have already cloned the repo and implemented approach 1 - this is very straightforward. 

Do you think this is a worthwhile addition and which approach do you favor?

If you think it is worthwhile, I am happy to implement the change and send a pull request.

**Comment by karianna** [comment]
@patrickvankann - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
