### ISSUE TITLE
Support for bulk insert (Adding Multiple Documents)

### ISSUE THREAD

**Issue by yaman** [vert-x/mod-mongo-persistor#43]
Is there any way to insert multiple documents at once? For the current code base, it seems that there is no support for sending bulk documents. Following functionality is what I need ;

```
db.products.insert( [ { _id: 11, item: "pencil", qty: 50, type: "no.2" },
                      {          item: "pen", qty: 20 },
                      {          item: "eraser", qty: 25 }
                    ] )
```

**Comment by karianna** [comment]
@yaman - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client

**Comment by Swasthikashree** [comment]
Is this enhancement request addressed in vert-x3?

**Comment by karianna** [comment]
@Swasthikashree - See https://github.com/vert-x3/vertx-mongo-client/issues/58
