### ISSUE TITLE
Add support for "distinct" query

### ISSUE THREAD

**Issue by johnoliver** [vert-x/mod-mongo-persistor#50]
http://api.mongodb.org/java/current/com/mongodb/DBCollection.html#distinct%28java.lang.String%29

Maybe in general we should just scan DBCollection and have a think about what we want to support on it

**Comment by karianna** [comment]
@johnoliver - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
