### ISSUE TITLE
Descide which aditional MongoDB functions to support

### ISSUE THREAD

**Issue by johnoliver** [vert-x/mod-mongo-persistor#52]
A list of Mongo functions is at:
https://github.com/vert-x/mod-mongo-persistor/wiki/MongoDB-Functions

Should go through this list, see which are relevant and which we want to support.

**Comment by karianna** [comment]
@johnoliver - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
