### ISSUE TITLE
Using regex in matcher

### ISSUE THREAD

**Issue by aurabhi** [vert-x/mod-mongo-persistor#55]
I am trying run a find query which involves a mongo regex. 

JsonObject matcher = new JsonObject();
matcher.putString("name", "{$regex : '.*" + name + ".*'}" );

but this get translated as String and I don't get expected result. To over come that I tried this:

JsonObject matcher = new JsonObject();
matcher.putObject("name", new JsonObject("{$regex : '.*" + name + ".*'}"));

But this throws the below exception:
org.vertx.java.core.json.DecodeException: Failed to decode:Unexpected character ('$' (code 36)): was expecting double-quote to start field name
 at [Source: java.io.StringReader@1c6c0838; line: 1, column: 3]
	at org.vertx.java.core.json.impl.Json.decodeValue(Json.java:63)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:61)

Am I doing something wrong here?

**Comment by karianna** [comment]
@aurabhi - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
