### ISSUE TITLE
Support for standard insert and differentiate state between updated and upserted

### ISSUE THREAD

**Issue by ghost** [vert-x/mod-mongo-persistor#59]
The save functionality provided by the module is nice and make some cases easier to handle, but sometimes one need to perform an insert using a specific _id field and the information about whether the save was successful or not is really important (for concurrency purposes in my case)

The same also happens with update:  it doesn't matter if one document was modified or no document matched the criteria so an upsert happened, the message will alway be "number" : 1
Also in this case sometimes it's important to know what actually happened inside mongoDB

When I finish a project I'm working on I plan to take a look at the code but I'm really busy right now so I'm just giving my two cents, maybe someone else think this is a useful addition!

Anyway thanks a lot for this module!

**Comment by karianna** [comment]
@ghost - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
