### ISSUE TITLE
'Find' action that returns multiple documents does not project correctly when excluding fields from the result

### ISSUE THREAD

**Issue by petermares** [vert-x/mod-mongo-persistor#75]
When performing a 'find' action, if the result contains more than one result document, the 'keys' parameter is not honoured.

For example, the following find action completes correctly (i.e. returns a document without the _id field):

{"action":"find","collection":"testcoll","matcher":{"id":"c1ad32f3-3b74-0b3f-934d-07a15dc1023f"},"keys":{"_id":0}}

However, if no matcher is presented, the the 'keys' field seems to not be honoured:

{"action":"find","collection":"testcoll", "keys":{"_id":0}}

**Comment by karianna** [comment]
@petermares - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
