### ISSUE TITLE
Allow authentication against a database other than the one the Persistor is using

### ISSUE THREAD

**Issue by jhawksley** [vert-x/mod-mongo-persistor#78]
It would be useful (to us at least) to have this mod be able to authenticate against another Mongo DB, in the same way the mongo CLI '--authenticationDatabase' switch works.  This would enable us to then have all our users administered in one place, with appropriate role mappings for their individual databases.

Could be related to #52.

**Comment by karianna** [comment]
@jhawksley - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
