### ISSUE TITLE
How to query array and limit result

### ISSUE THREAD

**Issue by toriacht** [vert-x/mod-mongo-persistor#79]
Hi,

Apologies for the noob question, perhaps this is the incorrect forum. I am trying to convert the provided  JsonObject examples to query an array using . My raw working command is as follows:

    db["data-23-03-15"].find(
       {mktid:'1.345',
        players: { $elemMatch: { selid: 6395169 }
                 }
     },{"players.$": 1 }).pretty();

Where I match on mktid and selid but only return the element of the array that matches selid. Players is an array. Can I do this using mod-mongo-persistor?

**Comment by karianna** [comment]
Hi there, this is not the right forum I'm afraid.  Please try StackOverflow.

**Comment by toriacht** [comment]
ok, thanks for reply ...
