### ISSUE TITLE
Find operation throws org.bson.types.ObjectId in JSON Exception

### ISSUE THREAD

**Issue by toriacht** [vert-x/mod-mongo-persistor#80]
Hi,

I am performing  basic find operation as per below 

            // create the matcher configuration
            
            JsonObject matcher1 = new JsonObject();
            matcher1.putString("marketId", "4444");
            matcher1.putString("status", "BLUE")
....

           json = new JsonObject().putString("collection", "books-23-03-15")
                    .putString("action", "find")
                    .putObject("matcher", matcher1);

             JsonObject data = new JsonObject();
                data.putArray("results", new JsonArray());
                // and call the event we want to use
                vertx.eventBus().send("mongodb-persistor", json, new ReplyHandler(req, data));

But this  throws an error

         INFO: Webserver started, listening on port: 8888
         Mar 30, 2015 11:13:39 AM org.vertx.java.platform.impl.cli.Starter
         INFO: Succeeded in deploying module
        Mar 30, 2015 11:13:51 AM io.vertx~mod-mongo-persistor~2.1.1-org.vertx.mods.MongoPersistor-   1497405398
       SEVERE: Exception in Java verticle
         org.vertx.java.core.VertxException: Cannot have objects of class class org.bson.types.ObjectId in    JSON
	at org.vertx.java.core.json.JsonElement.convertMap(JsonElement.java:60)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:56)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:45)
	at org.vertx.mods.MongoPersistor.sendBatch(MongoPersistor.java:338)
	at org.vertx.mods.MongoPersistor.doFind(MongoPersistor.java:308)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:143)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:41)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Obviously call works fine via mongo etc. Any reason it would fail like this using mongo-persistor?

**Versions:**
MongoDB: 3.0.1
Vertx: 2.1.1
mod-mongo-persistor: 2.0.0-final

Thanks

**Comment by karianna** [comment]
What version of the persistor, vertx and monogo?

**Comment by toriacht** [comment]
Hi @karianna 

Many thanks for the reply....I updated the question with version details...

**Comment by karianna** [comment]
Can you try with the 2.1.1 mod mongo persistor?

**Comment by toriacht** [comment]
Hi again,

Apologies, that was a typo! I am using 2.1.1, I have updated version in question and included more of stack trace to confirm version..

**Comment by johnoliver** [comment]
I will look at this tonight, but it is related to #41 and #76

**Comment by johnoliver** [comment]
Also, I am not sure you are using the latest snapshot of the persister as your line numbers don’t seem to line up, may be worth trying the latest persister as there have been improvements in the object conversion area

**Comment by toriacht** [comment]
Sure, if I can update version to something newer than 2.1.1 I will but no newer tags obvious on github?

**Comment by karianna** [comment]
@toriacht you can just clone the git repo and use gradle to build yourself a 2.1.2-SNAPSHOT

**Comment by toriacht** [comment]
Hi @karianna , I did try! I didn't want to annoy you/confuse issue with some beginners gradle questions but i cannot get it to build. I realise this is  Gradle 101 issue but i can;t fix! All mvn projects etc build fine...

```
~/workspace/mod-mongo-persistor$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ebrigun/workspace/mod-mongo-persistor/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating root project 'mod-mongo-persistor'.
> Could not resolve all dependencies for configuration 'classpath'.
   > Artifact 'com.hazelcast:hazelcast:2.6@jar' not found.
```

**Comment by johnoliver** [comment]
I believe I have created a test that confirms that this is working at #81.

You should be able to build and install mongo by executing:

```
./gradlew install
```

in the root of the mod-mongo-persistor project. 

Let us know if you have any other issues

**Comment by toriacht** [comment]
Hi @johnoliver 

I cloned repo, git pull again to be sure up to date. I'm on master branch

```
./gradlew build
```
then
```
:~/workspace/mod-mongo-persistor$ ./gradlew install
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:javadoc UP-TO-DATE
:javadocJar UP-TO-DATE
:copyMod UP-TO-DATE
:pullInDeps
:modZip UP-TO-DATE
:sourceJar UP-TO-DATE
:signArchives SKIPPED
:install

BUILD SUCCESSFUL

```
I modify my code to use new **2.1.1-SNAPSHOT** but i get the same results

```
INFO: Webserver started, listening on port: 8888
Mar 30, 2015 9:47:37 PM org.vertx.java.platform.impl.cli.Starter
INFO: Succeeded in deploying module
Mar 30, 2015 9:47:50 PM io.vertx~mod-mongo-persistor~2.1.1-SNAPSHOT-org.vertx.mods.MongoPersistor-1134951375
SEVERE: Exception in Java verticle
org.vertx.java.core.VertxException: Cannot have objects of class class org.bson.types.ObjectId in JSON
	at org.vertx.java.core.json.JsonElement.convertMap(JsonElement.java:60)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:56)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:45)
	at org.vertx.mods.MongoPersistor.dbObjectToJsonObject(MongoPersistor.java:592)
	at org.vertx.mods.MongoPersistor.sendBatch(MongoPersistor.java:349)
	at org.vertx.mods.MongoPersistor.doFind(MongoPersistor.java:319)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:146)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:40)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

If there is a particular class/method  you need me to debug on I am glad to do so..

**Comment by johnoliver** [comment]
can you try setting the "use_mongo_types" property to true please

**Comment by toriacht** [comment]
hi again @johnoliver , many thanks for all the replies, I do appreciate it. Unfortunately still the same outcome..

My config.json

```
{
    "mongo-persistor" : {
        "address": "mongodb-persistor",
        "host": "localhost",
        "port": 27017,
        "pool_size": 10,
        "db_name": "mydb" ,
        "use_mongo_types": false
    }
}
```

**Comment by johnoliver** [comment]
that config has "use_mongo_types" set to false.

No it is nothing to do with your config. The issue is that when mongo creates a record it assigns it a unique id in the "_id" field, that has a type of ObjectId which is a mongo specific datatype that means nothing to json. So when the persister tries to parse it to json it breaks. This should have been fixed when the use_mongo_types flag is set to true as we then ask the mongo libs to do the mongo->json conversion that takes into account types that are present in mongo but not json.

I would make sure that you have use_mongo_types set to true as I am fairly sure that should work

**Comment by toriacht** [comment]
MY BAD! It was late, sorry about that. That fixes the issue, many thanks for all the replies

**Comment by johnoliver** [comment]
Yeah no problem. We should document this as it is not obvious behaviour. Also in my opinion we should work for ObjectIds even without use_mongo_types set as it basically forces anyone who creates records outside the persister to set this. The current state is an acceptable work around but not great.
