### ISSUE TITLE
Upgrade driver for using with Mongo 3

### ISSUE THREAD

**Issue by ajunge** [vert-x/mod-mongo-persistor#86]
The minimum driver should be 2.13.0
The lastest is 3.0.3

MongoLab is upgrading free instances to Mongo 3 so this is must before Sep 30th.

http://docs.mongodb.org/manual/release-notes/3.0-compatibility/#driver-compatibility-changes
http://docs.mongolab.com/20150930-maintenance-event/

**Comment by karianna** [comment]
We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
